name: comment_box
description: A simple Flutter comment box for posts and products.
homepage: https://github.com/adeleyeayodeji/comment_box
version: 0.0.18

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/img/
